land-use-trade-offs/luto-2.0

luto/data/__init__.py
luto/dataprep.py
luto/economics/agricultural/cost.py
luto/economics/agricultural/ghg.py
luto/economics/agricultural/transitions.py
luto/economics/non_agricultural/revenue.py
luto/economics/non_agricultural/transitions.py
luto/settings.py
luto/simulation.py
luto/solvers/solver.py
luto/tools/__init__.py
luto/tools/compmap.py
luto/tools/write.py

Notes:
- Moves the code to get water license fees to tools.__init__ so it can be reused for non-agricultural transition costs.

Fix: Environmental Plantings and GHG Emissions Fixes

---

luto/ag_managements.py
luto/data/__init__.py
luto/economics/agricultural/cost.py
luto/economics/agricultural/ghg.py
luto/economics/agricultural/quantity.py
luto/economics/agricultural/revenue.py
luto/economics/agricultural/transitions.py
luto/economics/agricultural/water.py
luto/settings.py

Adds the agricultural management option 'precision agriculture' to the model

Feat: Add precision agriculture

---

luto/ag_managements.py
luto/data/__init__.py
luto/economics/agricultural/cost.py
luto/economics/agricultural/ghg.py
luto/economics/agricultural/quantity.py
luto/economics/agricultural/revenue.py
luto/economics/agricultural/transitions.py
luto/economics/agricultural/water.py
luto/settings.py
luto/simulation.py
luto/solvers/solver.py
luto/tools/__init__.py
luto/tools/write.py

- Adds ecological grazing to the model
- Small fixes in the write module relating to agricultural management options
- Adds an AGRICULTURAL_MANAGEMENT_USE_THRESHOLD setting to settings.py: governs the min value an agr. management variable must for the cell to be considered using the corresponding agman option.

Feature: ecological grazing

---

luto/data/__init__.py
luto/economics/agricultural/ghg.py
luto/economics/agricultural/quantity.py
luto/settings.py
luto/simulation.py
luto/solvers/solver.py
luto/tools/__init__.py
luto/tools/compmap.py
luto/tools/spatializers.py
luto/tools/write.py

Fixes:
- Makes a separate ammap for each ag. man option so the options can be stacked in the output
- A fix for ecological grazing's GHG contributions, which were previously all zero
- Fix for production figures in the quantity comparison being way off due to AMs
- Fix a bug where (in edge cases) AM contributions were being applied to the wrong products

Fixes for agricultural management options

---

luto/economics/agricultural/cost.py
luto/economics/agricultural/ghg.py
luto/settings.py
luto/simulation.py
luto/solvers/solver.py
luto/tools/__init__.py
luto/tools/write.py

- Changes variable values to be fractional instead of binary
- Gets production and GHG figures from linear expressions in the model instead of re-calculating them

Fixes: commodity production and ghg figures

---

luto/tools/report/create_html.py
luto/tools/report/create_report_data.py
luto/tools/report/tools/__init__.py
luto/tools/report/tools/helper_func.py

Fixed this issue. The missing 2011 in the area plot is because of a bug in data processing (report/tools/__init_.get_AREA_lu). I forgot to include the year 2011 in an IF_ELSE switch when processing a special case where both 2010/2011 need to be cleaned.

Fix the missing 2011 in the Area graphing

---

luto/settings.py
luto/simulation.py
luto/tools/__init__.py
luto/tools/report/create_html.py
luto/tools/report/create_report_data.py
luto/tools/report/tools/__init__.py
luto/tools/report/tools/helper_func.py
luto/tools/report/tools/template_html/index.css
luto/tools/report/tools/template_html/index.html
luto/tools/report/tools/template_html/index.js
luto/tools/report/tools/template_html/pages/GHG_emissions.html
luto/tools/report/tools/template_html/pages/GHG_emissions.js
luto/tools/report/tools/template_html/pages/economics.html
luto/tools/report/tools/template_html/pages/economics.js
luto/tools/report/tools/template_html/pages/land-use_area.html
luto/tools/report/tools/template_html/pages/land-use_area.js
luto/tools/report/tools/template_html/pages/production.html
luto/tools/report/tools/template_html/pages/production.js
luto/tools/report/tools/template_html/pages/spatial_maps.html
luto/tools/report/tools/template_html/pages/water_usage.html
luto/tools/report/tools/template_html/pages/water_usage.js
luto/tools/report/tools/template_html/style.css
luto/tools/write.py

Fix label axis ticks on report graphing
Landuse area now computed from dvars

Fixing graphing ticks and calculate the landuse area using dvars

---

luto/helpers.py
luto/settings.py
luto/tools/report/tools/template_html/pages/land-use_area.js
luto/tools/write.py

Change the output files timestamp. Now all output files share the same timestamp with the root dir
Calculate the outputs for 2010 using RESFACTOR=1 regardless of settings.RESFACTOR

Fix timestamp in output file names; Always use RESFACTOR for outputs of 2010

---

luto/data/__init__.py
luto/economics/land_use_culling.py
luto/settings.py
luto/tools/report/create_html.py
luto/tools/report/create_report_data.py
luto/tools/report/tools/helper_func.py
luto/tools/report/tools/template_html/pages/GHG_emissions.js
luto/tools/report/tools/template_html/pages/land-use_area.js
luto/tools/write.py

Fix the settings importing;
Fix naming, and x-axis errors in the reporting.
Fix the GHG_Target when GHG_LIMITS_TYPE == 'dict'

Fix the settings importing; Fix naming,x-axis errors in the reporting.

---

luto/settings.py
luto/tools/write.py

add two functions: output cost of agricultural management and non-agricultural land use

add two functions: output cost of agricultural management and non-agricultural land use

---

luto/data/__init__.py
luto/economics/non_agricultural/biodiversity.py
luto/economics/non_agricultural/cost.py
luto/economics/non_agricultural/ghg.py
luto/economics/non_agricultural/quantity.py
luto/economics/non_agricultural/revenue.py
luto/economics/non_agricultural/transitions.py
luto/economics/non_agricultural/water.py
luto/settings.py
luto/simulation.py
luto/tools/__init__.py
luto/tools/report/data_tools/template_html/pages/production.js

Adds the non-agricultural land use 'BECCS' (Bioenergy with Carbon Capture and Storage) to LUTO

Add BECCS Land Use

---

luto/economics/agricultural/ghg.py
luto/economics/agricultural/revenue.py

Changes the SB revenue effects to be equal to the added GHG sequestration multiplied by carbon price.

Feat: Savanna Burning Revenue

---

luto/data.py
luto/economics/agricultural/transitions.py
luto/economics/agricultural/water.py
luto/economics/non_agricultural/transitions.py
luto/settings.py
luto/solvers/input_data.py
luto/solvers/solver.py

Fixes the water overusage issue due to creating too many agricultural management variables when reformulating the problem between years.

Fix: Reformulation of ag management vars

---

luto/solvers/solver.py

Fix for crashing of solves due to constraints not being removed properly between years.

Fix: update constraints not removing constraints properly

---

luto/solvers/solver.py

Fix for variable lower bounds being undefined when ag management options aren't reversible

Fix: variable lower bounds undefined

---

luto/solvers/solver.py
luto/tools/report/create_report_data.py
luto/tools/write.py

Fixes crashes resulting from the disabling of environmental limits (water, GHG and biodiversity)

Fix disabling of environmental limits

---

luto/data.py
luto/settings.py
luto/simulation.py
luto/solvers/solver.py
luto/tools/report/create_report_data.py
luto/tools/report/data_tools/colors.py
luto/tools/report/data_tools/parameters.py
luto/tools/report/map_tools/parameters.py
luto/tools/write.py
luto/tools/xarray_tools.py

Bench mark
Before moving `reprojecting to data` (2010-2015, RESFACTOR=10)
- Running: 20 min
- Writing: 15 min
After the moving
- Running: 27 min
- Writing: 5 min

Finally! I moved the "reprojecting dvars to match biodiversity map" to the `Data` class

---

luto/economics/agricultural/water.py
luto/simulation.py
luto/solvers/input_data.py
luto/solvers/solver.py
luto/tools/write.py

Adjusts water limits to be the minimum of:
- Historical limit plus the climate change yield delta (i.e. water yield in 2050 - water yield in year t) calculated using land-use in year t-1
- Water yield in year t calculated using land-use in year t-1

CC Impacts Water Delta Term in Water Limits

---

luto/settings.py
luto/solvers/solver.py

Implements the option to set the GHG emission constraint to be 'soft'.

GHG Soft Constraint

---

luto/data.py
luto/dataprep.py
luto/economics/agricultural/water.py
luto/economics/non_agricultural/water.py
luto/helpers.py
luto/settings.py
luto/simulation.py
luto/solvers/input_data.py
luto/solvers/solver.py
luto/tools/create_task_runs/bash_scripts/conda_env.yml
luto/tools/report/create_report_data.py
luto/tools/report/data_tools/__init__.py
luto/tools/report/data_tools/template_html/pages/GHG_emissions.html
luto/tools/report/data_tools/template_html/pages/GHG_emissions.js
luto/tools/report/data_tools/template_html/pages/biodiversity.html
luto/tools/report/data_tools/template_html/pages/biodiversity.js
luto/tools/report/data_tools/template_html/pages/economics.js
luto/tools/report/data_tools/template_html/pages/land-use_area.css
luto/tools/report/data_tools/template_html/pages/land-use_area.html
luto/tools/report/data_tools/template_html/pages/land-use_area.js
luto/tools/report/data_tools/template_html/pages/production.html
luto/tools/report/data_tools/template_html/pages/production.js
luto/tools/report/data_tools/template_html/pages/spatial_maps.js
luto/tools/report/data_tools/template_html/pages/water_usage.css
luto/tools/report/data_tools/template_html/pages/water_usage.html
luto/tools/report/data_tools/template_html/pages/water_usage.js
luto/tools/write.py
requirements.txt

New data required in the `input` directory. Please copy these data to the input directory
Water net yield outside LUTO study area calculated with historical level:
https://drive.google.com/file/d/1k5z03fLOe6A6Ou4MqMbVCJUgG3gHYWdm/view?usp=sharing
Biochar data:
https://docs.google.com/spreadsheets/d/1kUwdTAcCPMnsF6I9tiOchqbgiWx6YTX2/edit?usp=sharing&ouid=107836248161729105877&rtpof=true&sd=true

<New data required> Reimplement the water constraint; Use historical water_mrj in the solver, but report the climate change impact

---

luto/solvers/input_data.py
luto/solvers/solver.py

Fixes the deviation issue in timeseries solves with the soft GHG constraints.

Fix: Soft Greenhouse Gas Constraints

---

luto/data.py
luto/economics/agricultural/biodiversity.py
luto/economics/agricultural/cost.py
luto/economics/agricultural/transitions.py
luto/economics/non_agricultural/biodiversity.py
luto/economics/non_agricultural/transitions.py
luto/settings.py
luto/solvers/input_data.py
luto/solvers/solver.py
luto/tools/__init__.py
luto/tools/write.py

- Adds the option for biodiversity constraints to be soft (`settings.BIODIV_CONSTRAINT_TYPE` and `settings.BIODIV_PENALTY`)
- Adds major vegetation groups (BIODIVERSTIY_TARGET_GBF_3) to LUTO

Major vegetation groups and soft biodiversity constraints
